# TCL File Generated by Component Editor 13.0
# Sat Jul 23 20:04:36 GFT 2022
# DO NOT MODIFY


# 
# pdm2pcm_interface "pdm2pcm_interface" v1.0
# github.com/Lwao 2022.07.23.20:04:36
# Interface to convert PDM bit stream to PCM word
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module pdm2pcm_interface
# 
set_module_property DESCRIPTION "Interface to convert PDM bit stream to PCM word"
set_module_property NAME pdm2pcm_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My IP Cores"
set_module_property AUTHOR github.com/Lwao
set_module_property DISPLAY_NAME pdm2pcm_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pdm2pcm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file base2_mod.vhd VHDL PATH base2_mod.vhd
add_fileset_file cic.vhd VHDL PATH cic.vhd
add_fileset_file clkdiv.vhd VHDL PATH clkdiv.vhd
add_fileset_file comb.vhd VHDL PATH comb.vhd
add_fileset_file combn.vhd VHDL PATH combn.vhd
add_fileset_file config_regn.vhd VHDL PATH config_regn.vhd
add_fileset_file countern.vhd VHDL PATH countern.vhd
add_fileset_file downsampling.vhd VHDL PATH downsampling.vhd
add_fileset_file input_interface.vhd VHDL PATH input_interface.vhd
add_fileset_file input_interface_fifo.vhd VHDL PATH input_interface_fifo.vhd
add_fileset_file integrator.vhd VHDL PATH integrator.vhd
add_fileset_file integratorn.vhd VHDL PATH integratorn.vhd
add_fileset_file mux2.vhd VHDL PATH mux2.vhd
add_fileset_file mux4.vhd VHDL PATH mux4.vhd
add_fileset_file osr_sel.vhd VHDL PATH osr_sel.vhd
add_fileset_file output_interface.vhd VHDL PATH output_interface.vhd
add_fileset_file output_interface_fifo.vhd VHDL PATH output_interface_fifo.vhd
add_fileset_file pdm2pcm.vhd VHDL PATH pdm2pcm.vhd TOP_LEVEL_FILE
add_fileset_file regn.vhd VHDL PATH regn.vhd
add_fileset_file shift_regn.vhd VHDL PATH shift_regn.vhd
add_fileset_file subn.vhd VHDL PATH subn.vhd
add_fileset_file sumn.vhd VHDL PATH sumn.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL pdm2pcm
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file base2_mod.vhd VHDL PATH base2_mod.vhd
add_fileset_file cic.vhd VHDL PATH cic.vhd
add_fileset_file clkdiv.vhd VHDL PATH clkdiv.vhd
add_fileset_file comb.vhd VHDL PATH comb.vhd
add_fileset_file combn.vhd VHDL PATH combn.vhd
add_fileset_file config_regn.vhd VHDL PATH config_regn.vhd
add_fileset_file countern.vhd VHDL PATH countern.vhd
add_fileset_file downsampling.vhd VHDL PATH downsampling.vhd
add_fileset_file input_interface.vhd VHDL PATH input_interface.vhd
add_fileset_file input_interface_fifo.vhd VHDL PATH input_interface_fifo.vhd
add_fileset_file integrator.vhd VHDL PATH integrator.vhd
add_fileset_file integratorn.vhd VHDL PATH integratorn.vhd
add_fileset_file mux2.vhd VHDL PATH mux2.vhd
add_fileset_file mux4.vhd VHDL PATH mux4.vhd
add_fileset_file osr_sel.vhd VHDL PATH osr_sel.vhd
add_fileset_file output_interface.vhd VHDL PATH output_interface.vhd
add_fileset_file output_interface_fifo.vhd VHDL PATH output_interface_fifo.vhd
add_fileset_file pdm2pcm.vhd VHDL PATH pdm2pcm.vhd
add_fileset_file regn.vhd VHDL PATH regn.vhd
add_fileset_file shift_regn.vhd VHDL PATH shift_regn.vhd
add_fileset_file subn.vhd VHDL PATH subn.vhd
add_fileset_file sumn.vhd VHDL PATH sumn.vhd


# 
# parameters
# 
add_parameter word_width INTEGER 32
set_parameter_property word_width DEFAULT_VALUE 32
set_parameter_property word_width DISPLAY_NAME word_width
set_parameter_property word_width TYPE INTEGER
set_parameter_property word_width UNITS None
set_parameter_property word_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property word_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 config_reg_out readdata Output 24
add_interface_port avalon_slave_0 rdreq read Input 1
add_interface_port avalon_slave_0 config_reg_in writedata Input 24
add_interface_port avalon_slave_0 en_vec writebyteenable_n Input 2
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset rst reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset clock_reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end pdm_stream export Input 1
add_interface_port conduit_end pdm_clock export Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset clock_reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave pcm_output readdata Output word_width
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

